import enum


class CaseStatus(str, enum.Enum):
    NEW = "NEW"
    COLLECTING_EVIDENCE = "COLLECTING_EVIDENCE"
    EVIDENCE_VALIDATED = "EVIDENCE_VALIDATED"
    UNDER_REVIEW = "UNDER_REVIEW"
    VIOLATION_CONFIRMED = "VIOLATION_CONFIRMED"
    REPORT_READY = "REPORT_READY"
    SUBMITTED = "SUBMITTED"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    ACTION_TAKEN = "ACTION_TAKEN"
    REJECTED = "REJECTED"
    CLOSED = "CLOSED"


class Priority(str, enum.Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class EvidenceType(str, enum.Enum):
    SCREENSHOT = "SCREENSHOT"
    VIDEO = "VIDEO"
    IMAGE = "IMAGE"
    PUBLIC_POST = "PUBLIC_POST"
    PUBLIC_COMMENT = "PUBLIC_COMMENT"
    PUBLIC_PROFILE = "PUBLIC_PROFILE"
    PUBLIC_URL = "PUBLIC_URL"
    ARTICLE = "ARTICLE"
    ARCHIVE = "ARCHIVE"
    DOCUMENT = "DOCUMENT"
    API_RESPONSE = "API_RESPONSE"
    METADATA = "METADATA"


class EvidenceVerificationStatus(str, enum.Enum):
    PENDING = "PENDING"
    VERIFIED = "VERIFIED"
    FAILED = "FAILED"
    DUPLICATE = "DUPLICATE"


class ViolationCategory(str, enum.Enum):
    HARASSMENT = "HARASSMENT"
    THREATS = "THREATS"
    VIOLENCE = "VIOLENCE"
    HATE = "HATE"
    SEXUAL_CONTENT = "SEXUAL_CONTENT"
    CHILD_SAFETY = "CHILD_SAFETY"
    FRAUD = "FRAUD"
    IMPERSONATION = "IMPERSONATION"
    SPAM = "SPAM"
    SCAM = "SCAM"
    PHISHING = "PHISHING"
    PRIVACY_VIOLATION = "PRIVACY_VIOLATION"
    COPYRIGHT = "COPYRIGHT"
    TRADEMARK = "TRADEMARK"
    MALWARE = "MALWARE"
    ILLEGAL_CONTENT = "ILLEGAL_CONTENT"
    SELF_HARM = "SELF_HARM"
    PLATFORM_MANIPULATION = "PLATFORM_MANIPULATION"
    DECEPTIVE_PRACTICE = "DECEPTIVE_PRACTICE"
    OTHER = "OTHER"


class AssessmentStatus(str, enum.Enum):
    PENDING_REVIEW = "PENDING_REVIEW"
    CONFIRMED = "CONFIRMED"
    NOT_CONFIRMED = "NOT_CONFIRMED"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class ReportStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    READY = "READY"
    SUBMITTED = "SUBMITTED"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    REJECTED = "REJECTED"
    ACTIONED = "ACTIONED"
    CLOSED = "CLOSED"


class ReadinessLevel(str, enum.Enum):
    READY = "READY"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    INSUFFICIENT = "INSUFFICIENT"


class ReviewAction(str, enum.Enum):
    APPROVE = "APPROVE"
    REQUEST_MORE_EVIDENCE = "REQUEST_MORE_EVIDENCE"
    REJECT = "REJECT"
    RETURN_TO_OPERATOR = "RETURN_TO_OPERATOR"


class ReviewQueueStatus(str, enum.Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    NEEDS_MORE_EVIDENCE = "NEEDS_MORE_EVIDENCE"
    REJECTED = "REJECTED"
    RETURNED = "RETURNED"
